name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
  
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Miri
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: miri
    - run: cargo miri setup
    - name: Test with Miri
      run: cargo miri test

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
